version: '3.4'

services:
  db:
    image: postgres:11.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: tralalala
    networks:
      - overlay
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - overlay
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
  fe:
    build:
      context: fe
      dockerfile: Dockerfile
    restart: always
    networks:
      - overlay
    expose:
      - 1234
      - 1235
    ports:
      - 1234:1234
      - 1235:1235
    volumes:
      - './fe:/app'

networks:
  overlay:
