version: '3.4'

services:
  db:
    image: postgres:11.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: tralalala
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: hot-reload
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./:/app/
    links:
      - db
