version: '3.4'

services:
  db:
    image: postgres:11.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: tralalala
    networks:
      - overlay
  be:
    build:
      context: be
      dockerfile: Dockerfile
      target: hot-reload
    restart: always
    networks:
      - overlay
    expose:
      - 8080
    volumes:
      - './be:/app'
    depends_on:
      - db
  fe:
    build:
      context: fe
      dockerfile: Dockerfile
    restart: always
    networks:
      - overlay
    expose:
      - 1235
    ports:
      - 1235:1235
    volumes:
      - './fe:/app'
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx/web.template:/etc/nginx/conf.d/web.template
    networks:
      - overlay
    ports:
      - "8080:8080"
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/web.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - be
      - fe

networks:
  overlay:
